# Generated by Django 2.0 on 2019-10-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_No', models.CharField(max_length=100)),
                ('blood_Group', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pre_Health', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='login_details',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical.user_details'),
        ),
    ]
