# Generated by Django 2.0 on 2019-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='blood_Group',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='mobile_No',
            new_name='mobile_no',
        ),
        migrations.AddField(
            model_name='user_details',
            name='doc_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='doc_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='doc_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='family_doctor',
            field=models.IntegerField(default=0),
        ),
    ]
