# Generated by Django 2.0 on 2019-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0002_auto_20191014_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='emergency_contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
