# Generated by Django 2.0 on 2019-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0004_check_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up',
            name='next_date',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check_up',
            name='today_date',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
