# Generated by Django 2.0 on 2019-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0006_user_details_warn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='warn',
            field=models.IntegerField(default=0),
        ),
    ]
